language: java
env:
  global:
    - SONATYPE_RELEASE_SERVER=cna-releases
    - SONATYPE_SNAPSHOT_SERVER=cna-snapshots
    - SONATYPE_USERNAME=deployment
    - secure: "hD0aMholmskUgzxEqpNrFvngf3xDLMUDZdIRybH20qWn6wXvtlmxkDMH+1nA\ncVo3/OI0OAf+XadAJwS4WteICnuOgQIufvj6tCt02N/XJxBA7Ga4siVO5RK2\neJGFH/+14d0piX8Oyqs/Ighoes6Q9C7c/aGNCZDLUwWTpgdGKrc="
    
after_script:
  - python .mvnSettings.py
  - mvn clean deploy --settings ~/.m2/mySettings.xml
